name: Upload XTGeo release to PYPI

on:
  release:
    types: [created]

# Verify that wheel build jobs succeed
jobs:
  deploy_linux_cibuildwheel:
    name: CIBW deploy ${{ matrix.cibw_python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CIBW_BEFORE_TEST: >
        pushd {project} &&
        pip install -r requirements/requirements.txt &&
        pip install -r requirements/requirements_test.txt &&
        git clone --depth 1 https://github.com/equinor/xtgeo-testdata ../xtgeo-testdata
      CIBW_TEST_COMMAND: >
        pushd {project} &&
        pytest tests --disable-warnings --hypothesis-profile ci
      CIBW_BUILD: ${{ matrix.cibw_python }}-manylinux_x86_64
      CIBW_MANYLINUX_X86_64_IMAGE: manylinux2010

    strategy:
      matrix:
        os: [ubuntu-latest]
        cibw_python: [cp36, cp37, cp38, cp39]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: >
          python -m pip install pip -U &&
          python -m pip install wheel &&
          python -m pip install cibuildwheel

      - name: Build wheels and test
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - name: Publish to PYPI Linux
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_SECRET }}
        run: >
          pip install twine &&
          twine upload wheelhouse/*

  deploy_macos_cibuildwheel:
    name: CIBW deploy ${{ matrix.cibw_python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CIBW_BEFORE_TEST: >
        pushd {project} &&
        pip install -r requirements/requirements.txt &&
        pip install -r requirements/requirements_test.txt &&
        git clone --depth 1 https://github.com/equinor/xtgeo-testdata ../xtgeo-testdata
      CIBW_TEST_COMMAND: >
        pushd {project} &&
        pytest tests --disable-warnings
      CIBW_BUILD: ${{ matrix.cibw_python }}-macosx_x86_64

    strategy:
      matrix:
        os: [macos-latest]
        python-version: [3.8] # PY version for "Install cibuildwheel", default is 2.7!
        cibw_python: [cp36, cp37, cp38, cp39]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: >
          python -m pip install pip -U &&
          python -m pip install wheel &&
          python -m pip install cibuildwheel

      - name: Build wheels and test python < 3.9
        if: matrix.cibw_python != 'cp39'
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - name: Build wheels and test python 3.9
        if: matrix.cibw_python == 'cp39'
        # note tests are a bit restricted due to missing pytables wheel; that is
        # --ignore tests/test_well
        env:
          CIBW_TEST_COMMAND: >
            pushd {project} &&
            pytest tests --disable-warnings --ignore tests/test_well

        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - name: Publish to PYPI MacOS
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_SECRET }}
        run: >
          pip install twine &&
          twine upload wheelhouse/*

  # pitfall for Windows, while this works for linux and macos:
  # run: |
  #    command1
  #    command2
  # it will not work for windows! Only command1 is executed; hence this syntax is
  # replaced with:
  # run: >
  #     command1 &&
  #     command2

  deploy_windows_cibuildwheel:
    name: CIBW deploy ${{ matrix.cibw_python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CIBW_BEFORE_TEST: >
        pushd {project} &&
        pip install -r requirements/requirements.txt &&
        pip install -r requirements/requirements_test.txt &&
        git clone --depth 1 https://github.com/equinor/xtgeo-testdata ../xtgeo-testdata

      # a test with forks is skipped as this calls python in a subprocess, where
      # the cibuildwheel on windows cannot find the xtgeo module
      CIBW_TEST_COMMAND: >
        pushd {project} &&
        pytest tests --disable-warnings --ignore-glob="*forks.py"
      CIBW_BUILD: ${{ matrix.cibw_python }}-win_amd64

    strategy:
      matrix:
        os: [windows-latest]
        cibw_python: [cp36, cp37, cp38, cp39]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: >
          python -m pip install pip -U &&
          python -m pip install wheel &&
          python -m pip install cibuildwheel

      - name: Build wheels and test python < 3.9
        if: matrix.cibw_python != 'cp39'
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - name: Build wheels and test python 3.9
        if: matrix.cibw_python == 'cp39'
        # note tests are a bit restricted due to missing pytables wheel
        env:
          CIBW_TEST_COMMAND: >
            pushd {project} &&
            pytest tests --disable-warnings --ignore tests/test_well
            --ignore-glob="*forks.py" -x
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - name: Publish to PYPI Windows
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_SECRET }}
        run: >
          pip install twine &&
          twine upload wheelhouse/*
