name: Upload XTGeo release to PYPI

on:
  release:
    types: [created]

env:
  CIBW_BEFORE_ALL_LINUX: "sh scripts/swig_manylinux.sh"
  CIBW_BEFORE_ALL_WINDOWS: "choco install -y --no-progress --allow-empty-checksums -r swig --version=4.0.1"
  CIBW_BEFORE_ALL_MACOS: "brew install swig"
  CIBW_TEST_COMMAND: "python -c \"import xtgeo; print(xtgeo.__version__)\""
  CIBW_BUILD: |
    cp36-manylinux_x86_64
    cp37-manylinux_x86_64
    cp38-manylinux_x86_64
    cp36-macosx_x86_64
    cp37-macosx_x86_64
    cp38-macosx_x86_64
    cp36-win_amd64
    cp37-win_amd64
    cp38-win_amd64

jobs:
  build_wheels:
    name: Deploy wheels to PYPI for ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.5.5

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - name: Check wheels and paths (ubuntu only)
        run: |
          ls -l wheelhouse
          ls -latr
        if: matrix.os == 'ubuntu-18.04'

      - name: Publish to PYPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          pip install twine
          twine upload wheelhouse/*
